### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [ricn/librex#8]
Hello, I want to contribute for librex and i designed a logo. What do u think this logo. If you want it, i will send a pr. Or If you want something else, you can say it.

I used libre office color and elixir color.

![librex](https://user-images.githubusercontent.com/36298335/41968030-e2394dea-7a0b-11e8-99a6-04caa7fd814a.jpg)

**Comment by ricn** [comment]
Nice! The second one looks great :-)

**Comment by reallinfo** [comment]
Well! I added the all version (logomark, horizontal, vertical)

Also, i updated the readmefile.

https://github.com/ricn/librex/pull/9

**Comment by ricn** [comment]
Thanks!

**Comment by reallinfo** [comment]
You're welcome!
